### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by JeffreyDavidsz** [comment]
Is the GitHub workflow a new thing?

**Comment by peternewman** [comment]
> Is the GitHub workflow a new thing?

In what sense? GitHub Actions has existed for ages. I think a few people have done Companion workflows, certainly I stole and adapted this from others.

**Comment by JeffreyDavidsz** [comment]
The Github flow is usually only used for building. I havent seen it being used to build just the module. It makes sense for testing by others than the maintainer though

**Comment by peternewman** [comment]
Ah gotcha.

Yeah I also use it to check prettier and have found it handy if I need to make a quick tweak to fix a bug in a module in the field without needing a full build environment as it will generate a module with all the required packages already installed.

I've also used it to run some basic tests too in the past:
https://github.com/bitfocus/companion-module-sony-bravia/blob/ce35e94656c87bb61a4e44ec282dea78bd856f5b/.github/workflows/node.yaml#L31-L35

The testing by other maintainers will become more relevant in a future PR fairly soon...

**Comment by JeffreyDavidsz** [comment]
Just to be clear I haven't include it in the beta builds, when ready please request it on Slack

**Pull request merged**
